version: "3.4"
services:

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    image: yarp/security/gateway:dev

  api:
    build:
      context: .
      dockerfile: Weather.Api/Dockerfile
    image: yarp/security/api:dev

  web:
    build:
      context: .
      dockerfile: Weather.Web/Server/Dockerfile
    image: yarp/security/web:dev