version: "3.4"
services:

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    image: ${DOCKER_REGISTRY}yarp/security/gateway:${TAG:-dev}
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=7001
      - "Authority=https://idsrv"
    ports:
      - 7001:443

  idsrv:
    build:
      context: .
      dockerfile: DevIdentityServer/Dockerfile
    image: ${DOCKER_REGISTRY}yarp/security/idsrv:${TAG:-dev}
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=5001
    ports:
      - 5001:443

  api:
    build:
      context: .
      dockerfile: Weather.Api/Dockerfile
    image: ${DOCKER_REGISTRY}yarp/security/api:${TAG:-dev}
    ports:
      - 5149:8080

  web:
    build:
      context: .
      dockerfile: Weather.Web/Server/Dockerfile
    image: ${DOCKER_REGISTRY}yarp/security/web:${TAG:-dev}
    ports:
      - 5022:8080