security:
  clients:
    - clientId: "gui"
      allowedGrantTypes:
        - client_credentials
#        - hybrid
        # - password
        # - delegation
        # - token-exchange
        - authorization_code
        # - implicit
#      requirePkce: true
      redirectUris:
        - https.+
      allowedScopes: # scopes that app can request
        - api1.read
        - profile
        - openid
      requireConsent: false # is the user prompted for concept are scopes autogranted
      AllowOfflineAccess: true
      AccessTokenLifetime: 300
      clientSecrets:
        - value: password
  apiResources:
    - name: "app1"
      displayName: "app1"
      scopes:
        - name: app1.read
        - name: openid
  users:
    - subjectId: user@test.com
      username: user
      password: p@ssw0rd
    - subjectId: admin@test.com
      username: admin
      password: p@ssw0rd