apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: tls-certificate
type: kubernetes.io/tls
data:
  tls.crt: QmFnIEF0dHJpYnV0ZXMNCiAgICBsb2NhbEtleUlEOiAwMSAwMCAwMCAwMCANCiAgICBmcmllbmRseU5hbWU6IEFTUC5ORVQgQ29yZSBIVFRQUyBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZQ0Kc3ViamVjdD1DTiA9IGxvY2FsaG9zdA0KaXNzdWVyPUNOID0gbG9jYWxob3N0DQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0NCk1JSUREVENDQWZXZ0F3SUJBZ0lKQUplT2pSaUw1VzdzTUEwR0NTcUdTSWIzRFFFQkN3VUFNQlF4RWpBUUJnTlYNCkJBTVRDV3h2WTJGc2FHOXpkREFlRncweU1qQTVNRFl4T0RNMk1USmFGdzB5TXpBNU1EWXhPRE0yTVRKYU1CUXgNCkVqQVFCZ05WQkFNVENXeHZZMkZzYUc5emREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MNCmdnRUJBTXpWVFluckNDTDBFMUtvT1pEQWlyZkUwdVp4N01wcjVRcWFFRE5RamRMYzFCV25wZFFRaFJXL1lQSUINCnJRV3RtZzB2TUFRLy9RdTAzZnh3bUxGTGQyam1uR0ZGS1UyMEJWM0Mwd3RhSk9kVm8yL1dpa2ZwQXRQS3lyMk4NCnF1S3BYK3FPMWJFY2dUZHpFOWRHWXowUGlKYXpsbnFWaXJxbVR3MVlVNVFJZ2NxZ3ZOSFk5MWtsSzVHcjRMNjkNCnRtazVjL2RzMnhrdU5xVkptUWVZVUJtUFJ5ZEE0bWlKeUtsTzBWL1ZJbFo5aWxEMFoyNUNHbFg2MUhqYjVxZ2oNCmVjVkExTHh6dG90R2xlYlJXYUVUN0FQVTdTVWVBQzZTSDdWKzJJZGppd3JJemdyUS9aTGV3YUJhT0xxWVJ0VXINCnFBRDRxa1NqWHBPaDU3VlMyNnZRcEF4Ti9UVUNBd0VBQWFOaU1HQXdEQVlEVlIwVEFRSC9CQUl3QURBT0JnTlYNCkhROEJBZjhFQkFNQ0JhQXdGZ1lEVlIwbEFRSC9CQXd3Q2dZSUt3WUJCUVVIQXdFd0Z3WURWUjBSQVFIL0JBMHcNCkM0SUpiRzlqWVd4b2IzTjBNQThHQ2lzR0FRUUJnamRVQVFFRUFRSXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUINCkFFc053UXJpZ2RvK1Y3RVphZ2JvZU9tc2dKVTFkemdEbWxEdVFYL3JqWm43cnlYQUVhbkpUd2VvaFJ2amVFeFkNCjVxVWxxUkt2bmpKZHR2czQ0Q0J0S1VqbzZwZlZoZDRPTjByeFIzamtsdXNQYkgvb2VDUDhKVWpZTzI1SnB6STgNCjZzRDZmdEZSMndhN2hxSUVUaFVXK0l4a3ozUkt6WVJZVHR6L1NMK3hmVkdtYWVLbzJaNEtkR21idTRvNHpISlUNCldML2xyeHRzd0RPWDZWM1czeUtYYnZkQWhUek9NbC9kYk5kUEpuNWk0THIzK29RZVJDWFppc2xGajhPY3kxWXQNCjk5cS91c3NkbXl2SllRYllSTE1Dc3laVVFleTNYZTJ1MmRFWUJrQVJuTFFJQUZyaGpiRjVGdFUvN1FFVUo2MVgNCmpvZktZQ1M0WUFmYitsRlNiV0hSZUw0PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURNMVUySjZ3Z2k5Qk5TDQpxRG1Rd0lxM3hOTG1jZXpLYStVS21oQXpVSTNTM05RVnA2WFVFSVVWdjJEeUFhMEZyWm9OTHpBRVAvMEx0TjM4DQpjSml4UzNkbzVweGhSU2xOdEFWZHd0TUxXaVRuVmFOdjFvcEg2UUxUeXNxOWphcmlxVi9xanRXeEhJRTNjeFBYDQpSbU05RDRpV3M1WjZsWXE2cGs4TldGT1VDSUhLb0x6UjJQZFpKU3VScStDK3ZiWnBPWFAzYk5zWkxqYWxTWmtIDQptRkFaajBjblFPSm9pY2lwVHRGZjFTSldmWXBROUdkdVFocFYrdFI0Mithb0kzbkZRTlM4YzdhTFJwWG0wVm1oDQpFK3dEMU8wbEhnQXVraCsxZnRpSFk0c0t5TTRLMFAyUzNzR2dXamk2bUViVks2Z0ErS3BFbzE2VG9lZTFVdHVyDQowS1FNVGYwMUFnTUJBQUVDZ2dFQURhcnArcHJ4Tnd2Y1FqYXhhS1JBWFZUSDBkS21QemVGMS9oQnZuclFpOUpxDQpZR3VJV0NjbUNqWno3SklLRG9mdjhKTkdlL0lkRzJ2ZEtCd0hSRVZKMlhrUjFEZStNczRoVVlsUGRjRjFGdTZTDQo4a0o1aGFUWnFISXVwd2xON3NQb2Y0azZYeEFNMnp0VmhwYk94bU5EOVBKVXh5YzFVNUVIVTFlaWRBMUJROWpwDQpTVEJwR0NCdG5DNThHRUpMcnZHUVI3dllUYXl2NEx6amZDSGtaZHYrV1Z3R0VjemRobXh3dk40Sm9CeXJpOG1IDQp1UmFyL2xxNFpQa1RvUGI0dGovWmIyQm9EM3p6bTdGcldydjVpb2FJUE55anJtMjZYVlFqMmc1eThzMHFXOEJKDQpDdnBqYW5LcVplSlM5Nzk5bVZzU0JsRVA0RzJoc0JTNEVIT09BVnNSdlFLQmdRRHZtcjVjZUhmTlNMMTFsSjRtDQpCNnJDc1FoSkdSVE1rd0NQYW9VaUZMc1k3bGZFRUFwYmswRHVLd25MZUY2aHJ3ek9WakhmRjdaMmJVbDkydXhvDQpRampZQjBpcjBaMnNXZ1pWM2EzdnRZTXFXb2h5UlJlT25iS0VpbGpPV2E0NnhlRkdsWnUvRVp0dHRMdEZvOVlsDQpzYVZWN3RvOFdmNEdtak9rRjZGZzRZek9wd0tCZ1FEYTJYUzkybzd4UHVwTjk3SlVhOG1oVlpzdjJ1MGYvZnczDQoraE1YRmRkalcxNlYxcGxYTzhHM1YwbkNWeHVYaHJ5M1V0REVvelZsUTRKemRDT1gyY0dVcXNIUmEzTEJsbFZuDQpLQy9ScUtUWU1iMmZoMllIN1k5K1RWZTM0SFQwQ3VKd0k2T3lYYTdoQUkxbHd4TUxiQWVzRU1LOXpHNXNyMFA0DQo3aEZET3hWTXd3S0JnUUNaWHJZSFB0MkF1OVQ2VkowK3ZwMmhiZXhkemY0d1ROQ0kvS2duZnBtY2hjUU1MakJUDQpHZGp3R3dCMEM2S1hZQk9VYUR3WUQzZXVLcHBtUXlJY1FuZGNZSjAxemtGZE4ycml2N2s4dlRVdWdURGg1RFFHDQpDQTlqSTZOZ3dxcngyQVF4U0VhZmNVZktXMnVjVWhrYm03QzNadUt1eXZQOWllc1FXRWZtV2JubDlRS0JnRWNaDQoxeC9IWGlGcXUxelJXSktzNGprVVF2THRRWlRmUTQ0OEpPK2ZIUGNldkVBYUZIK08zb1RlU3d4a21JWkdOQkdyDQpTa0JZZGdTTVJsbVVKZXd6eHZ5eDdYNUlWbVFtbjJDQVllalB6WjZmcW1lbDZiUXhyaWp1bjgwUmsyMm1DNk03DQpNUGZHRUFieDB2NTR2anM3d2RKWkw2dlNPeDM4WXkwQXk0TDRNeGRaQW9HQkFLNFpXTmI5VlZFRHJIZlp5RlN1DQpvNzRwNVlyTUV0d1JvSzNFM3dGUEswRWt6S0JoOVk2djkxKy9OTDlHSU45cUdzZFltTjhzbExVcUtQNFJ4aFEyDQowcjBybE9MdW5CMjFnQWs0OWM3ZDUwb1QzY2kxelk2T0RuVS9NbWUwWEJGMlJXY1EzVExrWkQ0ZlgwU3NnL1BpDQpxQnhYQXhzUlpENS8xbFdsVmhHZCtwVSsNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k" # this is needed to accept the OIDC cookie from the IDP
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
            path: /api/
          - pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
            path: /swagger
          - pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
            path: /
  tls:
    - hosts:
      - localhost
      secretName: tls-certificate